services:
  db:
    image: postgres:17.6-alpine3.22
    container_name: rota42_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rota42
      POSTGRES_USER: rota42
      POSTGRES_PASSWORD: pg@R0t4!42
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rota42_network

  db_explorer:
    image: dpage/pgadmin4:9.7.0
    container_name: rota42_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rota42.com
      PGADMIN_DEFAULT_PASSWORD: admin@R0t4!42
    ports:
      - "8181:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - rota42_network

volumes:
  postgres_data:
      name: rota42_volumes_db
  pgadmin_data:
      name: rota42_volumes_pgadm

networks:
  rota42_network:
    driver: bridge
    name: rota42_network