services:
    postgre:
        image: postgres:${POSTGRE_VERSION:-13.16}
        container_name: ${PROJECT_NAME:-fake_shop}_postgre
        restart: ${RESTART_POLICY:-always}
        environment:
            POSTGRES_USER: ${DB_USER:-ecommerce}
            POSTGRES_DB: ${DB_NAME:-ecommerce}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-Pg1234}
        ports:
            - "${DB_PORT:-5432}:5432"
        volumes:
            - postgre_data:/var/lib/postgresql/data
        networks:
            - fake_shop_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-ecommerce} -d ${DB_NAME:-ecommerce} || exit 1"]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 30s

    ecommerce:
        image: ${FAKE_SHOP_IMAGE:-fabricioveronez/fake-shop}
        container_name: ${PROJECT_NAME:-fake_shop}_ecommerce
        restart: always
        environment:
            DB_HOST: ${DB_HOST:-postgre}
            DB_USER: ${DB_USER:-ecommerce}
            DB_PASSWORD: ${DB_PASSWORD:-Pg1234}
            DB_NAME: ${DB_NAME:-ecommerce}
            DB_PORT: "${DB_PORT:-5432}"
            FLASK_APP: ${FLASK_APP:-index.py}
        ports:
            - "${APP_PORT:-5000}:5000"
        depends_on:
            postgre:
                condition: service_healthy
        networks:
            - fake_shop_network


networks:
   fake_shop_network:
        driver: bridge
        name: ${PROJECT_NAME:-fake_shop}_network

volumes:
    postgre_data:
        name: ${PROJECT_NAME:-fake_shop}_volume_db